### ISSUE TITLE
WeChat contact

### ISSUE THREAD

**Issue by Joysr** [Kirkkt/dot-files#4]
Hello,

I'm so sorry to open a such improper issue and disturb you in this way, as the wechat-id given to me could not be found in wechat. I tried a lot of similar combinations but got no surprise. I also searched for other contacts in google and baidu. At last, I think maybe it's the best way to contact with you in GitHub, because I've seen some new commits. :)
Could you please send me your contact again? You could find my contacts in my resume. There is also an online version: https://joysr.com/resume.

Thanks a lot in advance! 

Please feel free to edit this issue report for your convenience as it's not related to any dot files.
Have a good evening!

**Comment by Kirkkt** [comment]
Ha, I appreciate the effort. Close it for now since we are now connected on wechat :)
